apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: flask-web-app
          image: vamsi12358/flaskapplication:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
